# ============================
# Dataset Directory
# ============================
[Paths]
# Single data directory containing all data (will be split into k folds)
data_dir = "./data/"
save_model_pth = "./model/model.pth"
save_csv_pth = "loss_history.csv"

# ============================
# Hyperparameters
# ============================
[Hyperparameters]
learning_rate = 1e-5
batch_size = 32
num_epochs = 30
num_workers = 10
image_height = 400
image_width = 400
pin_memory = true
train = true
n_splits = 5
random_seed = 42
patience = 5
min_delta = 0.001
