# ============================
# Dataset Directories
# ============================
[Paths]
train_data_dir = "./train/"
val_data_dir =  "./val/"
save_model_pth = "./model/model.pth"
save_csv_pth = "loss_history.csv"

# ============================
# Hyperparameters
# ============================
[Hyperparameters]
learning_rate = 1e-5
batch_size = 128
num_epochs = 30
num_workers = 8
image_height = 400
image_width = 400
pin_memory = true
load_model = false
train = true
patience = 3
min_delta = 0.001