# ============================
# Paths
# ============================
[Paths]
model_pth = "./model/model_good.pth"                # Path to model
tif_pth = "./data_test/belieze.tif"                 # Path to tif raster file
output_dir = "./output/"                            # Save directory for mask/overlayed outputs

# ============================
# Parameters
# ============================
[Parameters]
tile_size=800                                       # Tile size (400 is recommended for now)
score_threshold=0.1                                 # Masks to keep
mask_threshold = 0.1                                # Define what is a mask pixel
