# ============================
# Paths
# ============================
[Paths]
model_pth = "./model/model_good.pth"                # Path to model
img_pth = "./data_test/belieze.tif"                 # Path to tif raster file
output_dir = "./output/"                            # Save directory for mask/overlayed outputs

# ============================
# Parameters
# ============================
[Parameters]
tile_size=400                                       # Tile size (400 recommended)
score_threshold=0.2                                 # Masks to keep
mask_threshold=0.5                                  # Define what is a mask pixel
use_overlap=true                                    # Add filling tiles at 2x2 intersections
