# ============================
# Paths
# ============================
[Paths]
model_pth = "./model/model_good.pth"
tif_pth = "./data_test/belieze.tif"
output_dir = "./output/"

# ============================
# Parameters
# ============================
[Parameters]
tile_size=400
score_threshold=0.1
mask_threshold = 0.5
